export default [
  {
    "_id": "4550-A1",
    "course": "4550",
    "title": "A1 - ENV + HTML",
    "details": "<span class='text-danger'>Multiple Modules</span> | <b>Not available until</b> May 6 at 12:00am | <b>Due</b> May 13 at 11:59pm | 100 pts",
    "description": "The assignment is available online. Submit a link to the landing page of your Web application.",
    "points": 100,
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": ["Text Entry", "Website URL", "File Uploads"],
    "assignTo": "Everyone",
    "due": "2024-05-13",
    "availableFrom": "2024-05-06",
    "availableUntil": "2024-05-20"
  },
  {
    "_id": "4550-A2",
    "course": "4550",
    "title": "A2 - CSS + Bootstrap",
    "details": "<span class='text-danger'>Multiple Modules</span> | <b>Not available until</b> May 13 at 12:00am | <b>Due</b> May 20 at 11:59pm | 100 pts",
    "description": "Use Bootstrap components to format your layout. Deploy the finished application and submit your live link.",
    "points": 100,
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": ["Website URL"],
    "assignTo": "Everyone",
    "due": "2024-05-20",
    "availableFrom": "2024-05-13",
    "availableUntil": "2024-05-27"
  },
  {
    "_id": "4550-A3",
    "course": "4550",
    "title": "A3 - JavaScript + React",
    "details": "<span class='text-danger'>Multiple Modules</span> | <b>Not available until</b> May 20 at 12:00am | <b>Due</b> May 27 at 11:59pm | 100 pts",
    "description": "Create a single-page React application that dynamically updates the DOM based on user input.",
    "points": 100,
    "group": "PROJECT",
    "displayGradeAs": "Points",
    "submissionType": "Online",
    "onlineEntryOptions": ["Website URL", "Media Recordings"],
    "assignTo": "Everyone",
    "due": "2024-05-27",
    "availableFrom": "2024-05-20",
    "availableUntil": "2024-06-03"
  },

  {
    "_id": "3540-A1",
    "course": "3540",
    "title": "Placeholder Assignment 1 - Game Programming",
    "details": "<b>Due</b> May 10 at 11:59pm | 100 pts",
    "description": "Placeholder assignment for CS3540 Game Programming.",
    "points": 100,
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": ["Text Entry"],
    "assignTo": "Everyone",
    "due": "2024-05-10",
    "availableFrom": "2024-05-03",
    "availableUntil": "2024-05-17"
  },
  {
    "_id": "1113-A1",
    "course": "1113",
    "title": "Placeholder Assignment 1 - General Biology",
    "details": "<b>Due</b> May 15 at 11:59pm | 50 pts",
    "description": "Placeholder assignment for BIOL1113 General Biology.",
    "points": 50,
    "group": "LABS",
    "displayGradeAs": "Points",
    "submissionType": "On Paper",
    "onlineEntryOptions": [],
    "assignTo": "Everyone",
    "due": "2024-05-15",
    "availableFrom": "2024-05-08",
    "availableUntil": "2024-05-22"
  },
  {
    "_id": "1280-A1",
    "course": "1280",
    "title": "Placeholder Assignment 1 - French Film",
    "details": "<b>Due</b> May 18 at 11:59pm | 75 pts",
    "description": "Placeholder assignment for FRNH1280 French Film and Culture.",
    "points": 75,
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Letter Grade",
    "submissionType": "Online",
    "onlineEntryOptions": ["Text Entry"],
    "assignTo": "Everyone",
    "due": "2024-05-18",
    "availableFrom": "2024-05-11",
    "availableUntil": "2024-05-25"
  },
  {
    "_id": "3302-A1",
    "course": "3302",
    "title": "Placeholder Assignment 1 - Advanced Writing",
    "details": "<b>Due</b> May 12 at 11:59pm | 100 pts",
    "description": "Placeholder assignment for ENGW3302 Advanced Writing.",
    "points": 100,
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": ["File Uploads"],
    "assignTo": "Everyone",
    "due": "2024-05-12",
    "availableFrom": "2024-05-05",
    "availableUntil": "2024-05-19"
  },
  {
    "_id": "3000-A1",
    "course": "3000",
    "title": "Placeholder Assignment 1 - Data Science",
    "details": "<b>Due</b> May 20 at 11:59pm | 100 pts",
    "description": "Placeholder assignment for CS3000 Data Science.",
    "points": 100,
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": ["Website URL"],
    "assignTo": "Everyone",
    "due": "2024-05-20",
    "availableFrom": "2024-05-13",
    "availableUntil": "2024-05-27"
  },
  {
    "_id": "2800-A1",
    "course": "2800",
    "title": "Placeholder Assignment 1 - Logic and Computation",
    "details": "<b>Due</b> May 14 at 11:59pm | 80 pts",
    "description": "Placeholder assignment for CS2800 Logic and Computation.",
    "points": 80,
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Points",
    "submissionType": "Online",
    "onlineEntryOptions": ["Text Entry"],
    "assignTo": "Everyone",
    "due": "2024-05-14",
    "availableFrom": "2024-05-07",
    "availableUntil": "2024-05-21"
  },
  {
    "_id": "2310-A1",
    "course": "2310",
    "title": "Placeholder Assignment 1 - Digital Design",
    "details": "<b>Due</b> May 22 at 11:59pm | 120 pts",
    "description": "Placeholder assignment for EECE2310 Digital Design.",
    "points": 120,
    "group": "LABS",
    "displayGradeAs": "Points",
    "submissionType": "Online",
    "onlineEntryOptions": ["File Uploads"],
    "assignTo": "Everyone",
    "due": "2024-05-22",
    "availableFrom": "2024-05-15",
    "availableUntil": "2024-05-29"
  }
];