export default [
  {
    _id: "4550-A1",
    course: "4550",
    title: "A1",
    details:
      "<span class='text-danger'>Multiple Modules</span> | <b>Not available until</b> Sep 12 at 12:00am | <b>Due</b> Sep 20 at 11:59pm | 100 pts",
    description:
      "Submit a link to the landing page of your first Web application.",
    points: 100,
    group: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["Text Entry", "File Uploads"],
    assignTo: "Everyone",
    due: "2025-09-20",
    availableFrom: "2025-09-12",
    availableUntil: "2025-09-28",
  },
  {
    _id: "4550-A2",
    course: "4550",
    title: "A2",
    details:
      "<span class='text-danger'>Multiple Modules</span> | <b>Not available until</b> Sep 20 at 12:00am | <b>Due</b> Sep 25 at 11:59pm | 100 pts",
    description:
      "Apply design principles using CSS and Bootstrap components, customize typography, color, and layout.",
    points: 100,
    group: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["Website URL"],
    assignTo: "Everyone",
    due: "2025-09-25",
    availableFrom: "2025-09-20",
    availableUntil: "2025-09-27",
  },
  {
    _id: "4550-A3",
    course: "4550",
    title: "A3",
    details:
      "<span class='text-danger'>Multiple Modules</span> | <b>Not available until</b> Oct 5 at 12:00am | <b>Due</b> Oct 10 at 11:59pm | 100 pts",
    description:
      "Develop a React application that updates data and manages user interaction with components.",
    points: 100,
    group: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["Website URL"],
    assignTo: "Everyone",
    due: "2025-10-10",
    availableFrom: "2025-10-05",
    availableUntil: "2025-10-20",
  },
  {
    _id: "4400-A1",
    course: "4400",
    title: "A1",
    details:
      "<span class='text-danger'>Module 1</span> | <b>Not available until</b> May 5 at 12:00am | <b>Due</b> May 16 at 11:59pm | 100 pts",
    description:
      "Develop a parser that reads and validates S-expressions. Submit your implementation and a short report explaining your design choices.",
    points: 100,
    group: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["Text Entry", "File Uploads"],
    assignTo: "Everyone",
    due: "2024-05-16",
    availableFrom: "2024-05-05",
    availableUntil: "2024-05-23",
  },
  {
    _id: "4700-A1",
    course: "4700",
    title: "A1",
    details:
      "<span class='text-danger'>Networking Basics</span> | <b>Not available until</b> May 10 at 12:00am | <b>Due</b> May 21 at 11:59pm | 100 pts",
    description:
      "Implement a simple HTTP client using TCP sockets. Measure latency, response headers, and document your results in a brief report.",
    points: 100,
    group: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads"],
    assignTo: "Everyone",
    due: "2024-05-21",
    availableFrom: "2024-05-10",
    availableUntil: "2024-05-28",
  },
  {
    _id: "3650-A1",
    course: "3650",
    title: "A1",
    details:
      "<span class='text-danger'>System Programming</span> | <b>Not available until</b> May 8 at 12:00am | <b>Due</b> May 18 at 11:59pm | 100 pts",
    description:
      "Set up your Unix development environment. Write and compile basic C programs using Makefiles and system calls.",
    points: 100,
    group: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads", "Text Entry"],
    assignTo: "Everyone",
    due: "2024-05-18",
    availableFrom: "2024-05-08",
    availableUntil: "2024-05-25",
  },
  {
    _id: "2800-A1",
    course: "2800",
    title: "A1",
    details:
      "<span class='text-danger'>Module 1</span> | <b>Not available until</b> May 7 at 12:00am | <b>Due</b> May 14 at 11:59pm | 80 pts",
    description:
      "Complete exercises on logical equivalence, normal forms, and symbolic computation.",
    points: 100,
    group: "ASSIGNMENTS",
    displayGradeAs: "Points",
    submissionType: "Online",
    onlineEntryOptions: ["Text Entry", "File Uploads"],
    assignTo: "Everyone",
    due: "2024-05-14",
    availableFrom: "2024-05-07",
    availableUntil: "2024-05-21",
  },

  {
    _id: "1800-A1",
    course: "1800",
    title: "A1",
    details:
      "<span class='text-danger'>Discrete Structures</span> | <b>Not available until</b> May 9 at 12:00am | <b>Due</b> May 17 at 11:59pm | 100 pts",
    description:
      "Solve problems involving propositional logic, predicates, and proof techniques including direct and contrapositive proofs.",
    points: 100,
    group: "ASSIGNMENTS",
    displayGradeAs: "Points",
    submissionType: "Online",
    onlineEntryOptions: ["Text Entry"],
    assignTo: "Everyone",
    due: "2024-05-17",
    availableFrom: "2024-05-09",
    availableUntil: "2024-05-24",
  },
  {
    _id: "1210-A1",
    course: "1210",
    title: "A1",
    details:
      "<span class='text-danger'>Career Development</span> | <b>Not available until</b> May 11 at 12:00am | <b>Due</b> May 19 at 11:59pm | 50 pts",
    description:
      "Submit your updated one-page resume and LinkedIn profile for feedback and review. Focus on clarity, structure, and technical presentation.",
    points: 50,
    group: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["Website URL", "File Uploads"],
    assignTo: "Everyone",
    due: "2024-05-19",
    availableFrom: "2024-05-11",
    availableUntil: "2024-05-26",
  },
];
